version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: Install SDK 11
          command: wget https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.26%2B4/OpenJDK11U-jdk_x64_linux_hotspot_11.0.26_4.tar.gz &&
            tar -xvf OpenJDK11U-jdk_x64_linux_hotspot_11.0.26_4.tar.gz &&
            sudo mv jdk-11*/ /opt/jdk11 &&
            export JAVA_HOME=/opt/jdk11 &&
            export PATH=$PATH:$JAVA_HOME/bin

      - run:
          name: Build
          command: export JAVA_HOME=/opt/jdk11 &&
              export PATH=$PATH:$JAVA_HOME/bin &&
              mvn -B -DskipTests clean package

      - run:
          name: Test
          command: export JAVA_HOME=/opt/jdk11 &&
              export PATH=$PATH:$JAVA_HOME/bin &&
              mvn test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
 
