version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: Install SDK 21
          command: wget https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.3%2B9/OpenJDK21U-jdk_x64_linux_hotspot_21.0.3_9.tar.gz &&
            tar -xvf OpenJDK21U-jdk_x64_linux_hotspot_21.0.3_9.tar.gz &&
            sudo mv jdk-21*/ /opt/jdk21 &&
            export JAVA_HOME=/opt/jdk21 &&
            export PATH=$PATH:$JAVA_HOME/bin

      - run:
          name: Build
          command: export JAVA_HOME=/opt/jdk21 &&
              export PATH=$PATH:$JAVA_HOME/bin &&
              mvn -B -DskipTests clean package

      - run:
          name: Test
          command: export JAVA_HOME=/opt/jdk21 &&
              export PATH=$PATH:$JAVA_HOME/bin &&
              mvn test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
 
